import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/mainnav";  // Importa la barra de navegación
import Footer from "@/components/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Los-Duros - Subastas en Línea", 
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="page-container">
            <MainNav />
            <main className="main-content">
              {children}
            </main>
          </div>
          <Footer />    
      </body>
    </html>
  );
}
